import React, { Component } from 'react';
import {WebView, View} from 'react-native';
												

class Terminos extends Component{
    render() {
      return (
        <View style={{flex: 1}}>
          <View style={{height: '100%'}}>
            <WebView
              source={{
                html:
                  "<style>p{text-align:justify}</style>" +
                  "<p>" +"YiMi (Kiotrak SA de CV) (en lo sucesivo denominada Como “YiMi” o la “Compañía”), es una sociedad debidamente constituida conforme a las leyes de México." +"</p>" +
                  "<p>" +"YiMi y sus filiales prestan servicios de gestión y operación de flotilla en línea (en lo sucesivo denominados como los “Servicios”) en la aplicación YiMi Fleet y en los Sitios Web de YiMi. Se considera como Socios No Conductores a aquellos usuarios que accedan, naveguen o utilicen YiMi Fleet y los Sitios Web de YiMi (en lo sucesivo el “Socio No Conductor”). El Socio No Conductor podrá conectarse con usuarios que están accediendo, navegando o utilizando YiMi Conductor y Sitios Web de YiMi (en lo sucesivo denominado como el “Conductor”), entre ellos, que se haya conectado con un Socio No Conductor, en lo sucesivo denominado como 'Conductor Vinculado'. " +"</p>" +
                  "<p>" +"El Socio No Conductor se sujetará a los presentes Términos y Condiciones de Uso de YiMi Fleet (en lo sucesivo denominados como los “Términos y Condiciones”). El Socio No Conductor podrá representar legalmente a terceros para ayudarles a registrarse como usuarios de YiMi Conductor. Es obligación del Socio No Conductor asegurarse de que la persona acepte y se obligue a cumplir con todos Términos y Condiciones de YiMi Conductor, en caso contrario, el Socio No Conductor será considerado como obligado solidario de dicha persona.	" +"</p>" +
                  "<p>" +"Al utilizar las cuentas de usuario y contraseña de YiMi Fleet, el Socio No Conductor podrá acceder a YiMi Conductor. Sin embargo, el Socio No Conductor no podrá disfrutar de todos los servicios de YiMi Conductor hasta que haya cargado todos los documentos e información que se requieren, aprobados por YiMi y YiMi Conductor, y acepte obligarse conforme a todos los Términos y Condiciones de YiMi Conductor." +"</p>" +
                  "<p>" +"Antes de utilizar YiMi Fleet, lea los presentes Términos y Condiciones con atención (especialmente las partes resaltadas en negritas). Un Socio No Conductor no podrá acceder a ni utilizar Servicios hasta que provea toda la información y documentos requeridos, aprobados por YiMi Conductor y YiMi, y se obligue conforme a estos Términos y Condiciones.Antes de utilizar YiMi Fleet, lea los presentes Términos y Condiciones con atención (especialmente las partes resaltadas en negritas). Un Socio No Conductor no podrá acceder a ni utilizar Servicios hasta que provea toda la información y documentos requeridos, aprobados por YiMi Conductor y YiMi, y se obligue conforme a estos Términos y Condiciones." +"</p>" +
                  "<p>" +"Si el Socio No Conductor elige y utiliza los Servicios, se considerará que el Socio No Conductor ha leído y aceptado todos y cada uno de los términos establecidos en el presente documento y acuerda que los presentes Términos y Condiciones son vinculantes entre el Socio No Conductor y la Compañía.El Socio No Conductor observará los siguientes términos de buena fe al utilizar YiMi Fleet."+"</p>" +
                  "<p>" +"Los presentes Términos y Condiciones son aplicables para todos los usuarios o navegadores de YiMi Fleet, y están sujetos a modificación en cualquier momento como resultado de ajustes realizados a la política comercial. El Socio No Conductor deberá visitar frecuentemente esta página web y/o la aplicación YiMi Fleet para mantenerse al tanto de las modificaciones realizadas. Las modificaciones, términos u otros requerimientos expresamente especificados o integrados en la página web y/o en YiMi Fleet formarán parte integral de los presentes Términos y Condiciones, ciertas partes de los términos podrán ser sustituidas por los avisos legales, términos o requerimientos más actualizados expresamente especificados o integrados en la página web y/o en YiMi Fleet. Al aceptar los Términos y Condiciones, el Socio No Conductor reconoce que también ha leído con atención y aceptado dichos términos sustituidos o reemplazados. Si el Socio No Conductor sigue utilizando los servicios de la Compañía, se considerará que el Socio No Conductor ha aceptado los Términos y Condiciones actualizados, de lo contrario, el Socio No Conductor dejará de utilizar inmediatamente YiMi Fleet." +"</p>" +
                  "<p>" +"Los presentes Términos y Condiciones expresamente dejan sin efecto cualquier acuerdo o arreglo previo que la Compañía haya celebrado con el Socio No Conductor con el fin de usar YiMi Fleet y los Servicios. YiMi inmediatamente podrá dar por terminados los presentes Términos y Condiciones o cualquier Servicio con respecto al Socio No Conductor, o en general, dejar de ofrecer o negar el acceso a los Servicios o a cualquier parte de los mismo, si YiMi considera que el Socio No Conductor ha incurrido en cualquier incumplimiento." +"</p>" +
                  "<p>" +"Asimismo, YiMi se reserva el derecho de negarse a prestar los Servicios al Socio No Conductor o negar al Socio No Conductor el uso de Páginas Web, servicios o aplicaciones de YiMi sin causa alguna." +"</p>" +
                  "<p style='font-weight: bold;'>" +"1. Registro del Socio No Conductor" +"</p>" +
                  "<p>" +"1.1. Para utilizar los Servicios, el Socio No Conductor debe descargar YiMi Fleet, instalarla en su dispositivo móvil y completar exitosamente el proceso de registro. Al registrarse, el Socio No Conductor deberá asegurarse que toda la información que haya proporcionado sea precisa, completa y válida." +"</p>" +
                  "<p>" +"1.2. El Socio No Conductor reconoce y acuerda que una vez que sea un usuario registrado de YiMi Fleet, la cuenta de servicio del Socio No Conductor en la Compañía se abrirá de forma predeterminada. La cuenta y contraseña predeterminadas serán la cuenta y contraseña de la cuenta de YiMi Fleet del Socio No Conductor." +"</p>" +
                  "<p>" +"1.3. Si el Socio No Conductor suscribe los presentes Términos y Condiciones a nombre de otra persona, el Socio No Conductor deberá tener plena capacidad legal y de ejercicio de conformidad con el Código Civil Federal. Aquella persona que sea menor de 18 años, no podrá ser Socio No Conductor." +"</p>" +
                  "<p style='font-weight: bold;'>" +"2. Servicios" +"</p>" +
                  "<p>" +"2.1. Las personas que accedan, naveguen o utilicen YiMi Pasajero y los Sitios Web de YiMi (en lo sucesivo denominadas como “Pasajeros”) podrán disfrutar los servicios de contratación de transporte privado en línea con base en las necesidades de desplazamiento del Pasajero a través de interacción con información en línea y fuera de línea y en tiempo real y una efectiva adecuación de recursos fuera de línea a través del análisis de big data. A través de los Servicios, los Pasajeros podrán disfrutar de un servicio de transporte privado prestado por conductores o empresas independientes quienes obtienen información de las solicitudes de servicios por medio de YiMi Conductor. Por medio de YiMi Fleet, los Socios No Conductores pueden disfrutar de los Servicios, incluyendo administrar y organizar sus propios Vehículos Registrados, acceder a la información personal general del Conductor Vinculado, vincular Vehículos Registrados con Conductores que lo necesitan, desvincular Vehículos Registrados de un Conductor Vinculado, adquirir información detallada con relación a las solicitudes de su Conductor Vinculado, adquirir información sobre el estado de los Conductores Vinculados (en línea o fuera de línea), y adquirir los ingresos proporcionales de la solicitud a través del servicio de cobranza y distribución de YiMi." +"</p>" +
                  "<p>" +"2.2. El Socio No Conductor únicamente podrá subir información relacionada con los vehículos que legalmente haya ocupado o poseído y que haya registrado en YiMi Fleet (en lo sucesivo denominada como el “Vehículo Registrado”);" +"</p>" +
                  "<p>" +"2.3. El Socio No Conductor podrá vincular un Vehículo Registrado con más de un Conductor Vinculado;" +"</p>" +
                  "<p>" +"2.4. Un Conductor Vinculado podrá vincularse con más de un Vehículo Registrado;" +"</p>" +
                  "<p>" +"2.5. Cuando un Conductor Vinculado preste servicios de transporte para atender una solicitud en YiMi Conductor, el Conductor Vinculado sólo podrá vincularse con un vehículo." +"</p>" +
                  "<p>" +"2.6. El Socio No Conductor no difundirá ni revelará a ninguna persona, información personal de ningún Pasajero o Conductor que haya adquirido por los Servicios, salvo para efectos del Servicio o cuando haya obtenido dicha información legalmente a través de otras fuentes." +"</p>" +
                  "<p>" +"2.7. Para utilizar los Servicios, el Socio No Conductor deberá presentar a la Compañía cierta información personal. El Socio No Conductor se obliga a proporcionar la información personal que requiera YiMi Fleet de forma precisa, completa y actualizada. Si no cumple con dicha obligación, se podrá impedir al Socio No Conductor a acceder o utilizar los Servicios." +"</p>" +
                  "<p style='font-weight: bold;'>" +"3. Acuerdos y Garantías" +"</p>" +
                  "<p>" +"3.1. El Socio No Conductor únicamente cooperará con el Socio Conductor, que" +"</p>" +
                  "<p>" +"- Tenga buen historial de manejo;" +"</p>" +
                  "<p>" +"- Cumpla con todos los requisitos establecidos para ser un conductor calificado, en cualquier ley o reglamento aplicable;" +"</p>" +
                  "<p>" +"- Hable español como hispanoparlante promedio;" +"</p>" +
                  "<p>" +"- Cuente con Certificado de No-Antecedentes Penales;" +"</p>" +
                  "<p>" +"- No tenga antecedentes de conducir arriesgadamente;" +"</p>" +
                  "<p>" +"- No tenga antecedentes de conducir en estado de ebriedad;" +"</p>" +
                  "<p>" +"- No tenga antecedentes de drogadicción;" +"</p>" +
                  "<p>" +"- No tenga antecedentes de enfermedades que puedan poner en riesgo la seguridad del conductor y de los pasajeros;" +"</p>" +
                  "<p>" +"- No haya tenido un accidente de tráfico mayor en los últimos 3 años;" +"</p>" +
                  "<p>" +"- Que entienda lenguas extranjeras es un plus (para conversaciones simples);" +"</p>" +
                  "<p>" +"Las siguientes enfermedades o actos podrían poner en riesgo la seguridad de los pasajeros y del conductor:" +"</p>" +
                  "<p>" +"- Enfermedad cardiaca orgánica" +"</p>" +
                  "<p>" +"- Epilepsia" +"</p>" +
                  "<p>" +"- Síndrome de Meniere" +"</p>" +
                  "<p>" +"- Vértigo" +"</p>" +
                  "<p>" +"- Histeria" +"</p>" +
                  "<p>" +"- Enfermedad de Parkinson" +"</p>" +
                  "<p>" +"- Psicopatías" +"</p>" +
                  "<p>" +"- Demencia y enfermedades del sistema nervioso que afecten el uso de las extremidades" +"</p>" +
                  "<p>" +"- Tomar o inyectarse drogas, tomar fármacos psicotrópicos que crean dependencia por un tiempo prolongado, volverse adicto y no dejarlos;" +"</p>" +
                  "<p>" +"- Otras enfermedades o enfermedades infecciosas que impidan manejar con seguridad (como tuberculosis, paperas y otras enfermedades infecciosas que se contagien por el aire o por gotículas); y" +"</p>" +
                  "<p>" +"- Cualquier otra condición prevista en las leyes y reglamentos nacionales o medidas de implementación locales;" +"</p>" +
                  "<p>" +"3.2.   Los Vehículos Registrados del Socio No Conductor cumplirán con las siguientes condiciones:" +"</p>" +
                  "<p>" +"- Los Socios No Conductores poseerán y ocuparán legalmente los Vehículos Registrados y los Vehículos Registrados podrán transmitirse legalmente a otra parte para su posesión y uso;" +"</p>" +
                  "<p>" +"- El vehículo no deberá haber estado involucrado en un accidente vial mayor ni haberse inundado nunca;" +"</p>" +
                  "<p>" +"- El vehículo estará limpio y libre de polvo, sin daños ni rayones aparentes;" +"</p>" +
                  "<p>" +"- La placa de vehículo debe ser clara;" +"</p>" +
                  "<p>" +"- El vehículo no deberá tener ninguna modificación, decoración con pintura en aerosol, y no se permiten bocinas de radio manuales;" +"</p>" +
                  "<p>" +"- Las luces deberán utilizarse adecuadamente;" +"</p>" +
                  "<p>" +"- La decoración interior deberá estar limpia y ordenada, sin desgaste ni olores;" +"</p>" +
                  "<p>" +"- Los asientos deberán de estar limpios y ordenados, libres de desgaste o pliegues;" +"</p>" +
                  "<p>" +"- Los botones del vehículo deberán poderse utilizar normalmente;" +"</p>" +
                  "<p>" +"- No deberán contener calcomanías publicitarias, accesorios, banderines u otros adornos;" +"</p>" +
                  "<p>" +"- Buena calidad interna, el vehículo deberá estar colocado en las posiciones correctas;" +"</p>" +
                  "<p>" +"- Los vidrios del vehículo deberán contar con película instalada;" +"</p>" +
                  "<p>" +"- Los certificados y partes del vehículo deberán estar completos, en su caso, incluyendo el anuncio del seguro obligatorio, símbolo de protección ambiental verde, marca de inspección del vehículo, licencia de conducir, manual de mantenimiento, juego de herramientas, extintor de incendios, gato, llanta de refacción, encendedor y tapetes; y" +"</p>" +
                  "<p>" +"- Cualquier otro aspecto previsto en las leyes y reglamentos aplicables." +"</p>" +
                  "<p>" +"3.3. Es obligación del Socio No Conductor mantener todo el hardware o software del dispositivo móvil actualizado para que se adapta a los requerimientos vigentes en ese momento de YiMi Fleet. La Compañía no será responsable de ningún problema que pueda surgir cuando el Socio No Conductor no utilice la versión más reciente y actualizada de YiMi Fleet y/o utilice YiMi Fleet en cualquier dispositivo móvil que no cumpla con los requerimientos relevantes de YiMi Fleet. El Socio No Conductor acepta que la Compañía podrá actualizar los requerimientos de software y hardware del teléfono móvil de YiMi Fleet de tiempo en tiempo." +"</p>" +
                  "<p>" +"3.4. Al utilizar los Servicios, el Socio No Conductor también se obliga a lo siguiente:" +"</p>" +
                  "<p>" +"- El Socio No Conductor utilizará los Servicios o YiMi Fleet de buena fe;" +"</p>" +
                  "<p>" +"- El Socio No Conductor utilizará los Servicios o YiMi Fleet únicamente para uso personal y no revenderá los mismos a terceros;" +"</p>" +
                  "<p>" +"- El Socio No Conductor no utilizará los Servicios ni YiMi Fleet para un fin ilícito;" +"</p>" +
                  "<p>" +"- El Socio No Conductor no utilizará los Servicios ni YiMi Fleet para acosar u obstaculizar a otros ni a causar inconvenientes a otros;" +"</p>" +
                  "<p>" +"- El Socio No Conductor no afectará la operación normal de la red;" +"</p>" +
                  "<p>" +"- El Socio No Conductor no intentará dañar los Servicios ni YiMi Fleet; y" +"</p>" +
                  "<p>" +"- El Socio No Conductor cumplirá con todas las leyes aplicables del país/región, provincia y/o ciudad en donde el Socio No Conductor use la aplicación o los Servicios." +"</p>" +
                  "<p style='font-weight: bold;'>" +"4. Servicio y cuota de cooperación" +"</p>" +
                  "<p>" +"4.1. YiMi tiene un mecanismo de precio que se calcula con un algoritmo (en lugar del mecanismo de fijación de precios por kilometraje como se ve generalmente en los servicios de taxi) teniendo en cuenta una tarifa base, el tráfico, el tiempo del viaje y la distancia." +"</p>" +
                  "<p>" +"4.2. El Conductor acuerda que la Compañía podrá pagarle periódicamente o irregularmente por la cooperación antes mencionada con base en la norma sobre liquidación actualizada de tiempo en tiempo. El Conductor exprés podrá ser pagado después de completar su proceso de registro." +"</p>" +
                  "<p>" +"4.3. El Conductor Vinculado no podrá retirar ningún saldo de tarifas de su propia cuenta en YiMi Conductor, en cambio, el saldo de las tarifas será exclusivamente controlado por el Socio No Conductor primero, y el Socio No Conductor podrá distribuir la tarifa de acuerdo con la cantidad acordada con el Conductor Vinculado." +"</p>" +
                  "<p>" +"4.4. La tarifa y relación entre el Socio No Conductor y el Conductor Vinculado será acordada, salvo pacto contrario, por el Socio No-Conductor y el Conductor Vinculado. YiMi no será responsable por ninguna controversia que resulte por el cobro de tarifas y la relación entre el Conductor Vinculado y el Socio No Conductor." +"</p>" +
                  "<p>" +"4.5. El Socio No Conductor reconoce y acepta que todos y cada uno de los comprobantes fiscales que el Pasajero requiera por los servicios de transportación serán emitidos por el Socio No Conductor o el Conductor en calidad de Conductor Vinculado, según sea aplicable conforme a las leyes y reglamentos aplicables, y reconoce que el Socio No Conductor y el Conductor en calidad de Conductor Vinculado serán responsables solidarios por la emisión de comprobantes fiscales que reúnan los requisitos fiscales aplicables en México. Aunque YiMi podrá facilitarles a los Socios No Conductores y a los Conductores en calidad de Conductores Vinculados la emisión de comprobantes, YiMi no será responsable por la emisión de cualesquiera comprobantes requeridos por los Pasajeros por los servicios de transportación, ni será responsable de cualquier error o falla en la entrega de los comprobantes fiscales correspondientes." +"</p>" +
                  "<p>" +"4.6. El Socio No Conductor reconoce y acepta que YiMi podrá facilitar la emisión de los comprobantes fiscales que el Socio No Conductor o el Conductor estén obligados a emitir de conformidad con las leyes y reglamentos aplicables, El Socio No Conductor reconoce que dicha facilidad podrá consistir en la emisión de dichos comprobantes fiscales por parte de YiMi, o cualquier tercero designado por YiMi para tales efectos, a nombre y por cuenta del Socio No Conductor, en los términos de la regla 2.7.1.3. de la Resolución Miscelánea Fiscal para 2018 (o cualquier disposición que la sustituya), o mediante cualquier otro mecanismo que YiMi considere apropiado. El Socio No Conductor reconoce que ni YiMi ni cualquier tercero designado por YiMi para dicho propósito serán responsables por la emisión de los comprobantes fiscales derivados de la aplicación de dicha regla 2.7.1.3., requeridos por los Pasajeros por los servicios de transportación. Ni YiMi ni cualquier tercero designado por YiMi para tales efectos no serán responsables por cualquier error o falla en la emisión de los comprobantes fiscales aplicables." +"</p>" +
                  "<p>" +"4.6.1. Facturación" +"</p>" +
                  "<p>" +"El Socio No Conductor acepta y reconoce que durante el proceso de registro del Conductor en la aplicación YiMi Fleet, el Socio No Conductor proporcionará la información necesaria para determinar la estructura de facturación que será aplicable al El Socio No Conductor, y los términos y condiciones aplicables." +"</p>" +
                  "<p>" +"- Facturación por parte del El Socio No Conductor." +"</p>" +
                  "<p>" +"Será aplicable al El Socio No Conductor que durante el proceso de registro en la aplicación YiMi Fleet proporcionó su información fiscal completa, incluido su Registro Federal de Contribuyente ('RFC') y su Certificado de Firma Digital o ('CSD')." +"</p>" +
                  "<p>" +"YiMi, validará el RFC del El Socio No Conductor para determinar si el RFC está activo o inactivo. Si el RFC está inactivo, YiMi, a través de la aplicación YiMi Fleet, notificará dicha situación al Socio No Conductor." +"</p>" +
                  "<p>" +"Si el estado RFC del El Socio No Conductor está activo y el Socio No Conductor proporciona el CSD correspondiente, el Socio No Conductor acepta y reconoce los términos del Acuerdo de servicios de facturación, que se está ejecutando entre el Socio No Conductor y el Tercero que designe YiMi ('Tercero Autorizado'), según la cual el Tercero Autorizado procesará las facturas en nombre y nombre del Socio No Conductor con su CSD y su propio RFC. En este caso, el Socio No Conductor está obligado a mantener el CSD válido y renovarlo de acuerdo con las regulaciones fiscales vigentes." +"</p>" +
                  "<p>" +"En el caso de que el CSD del Socio No Conductor no se encuentre vigente o no sea válido, el Socio No Conductor se obliga a actualizar y proporcionar el nuevo CSD a YiMi, en caso de no actualizarlo, se considerará que el Socio No Conductor aceptó cambiar a la opción Facturación en nombre del Socio No Conductor por un tercero." +"</p>" +
                  "<p>" +"El Socio No Conductor autoriza expresamente a YiMi, a retener los honorarios que se pagarán al Tercero Autorizado por sus servicios de facturación, y a pagar aquellos a nombre del Socio No Conductor al Tercero Autorizado." +"</p>" +
                  "<p>" +"El Socio No Conductor acepta que YiMi podrá, a su entera discreción, absorber el pago de las tarifas del Tercero Autorizado en nombre del Socio No Conductor, como un incentivo temporal." +"</p>" +
                  "<p>" +"YiMi podrá decidir dejar de absorber el pago de esas tarifas en cualquier momento que lo considere conveniente." +"</p>" +
                  "<p>" +"El Socio No Conductor está de acuerdo, para todos los fines legales, que YiMi no será parte del Acuerdo de Servicios de Facturación. En este sentido, la participación de YiMi consiste en permitir que el Socio No Conductor acepte los términos del Acuerdo de Servicios de Facturación. El Tercero Autorizado será el único obligado y responsable de sus actos en virtud del Acuerdo de Servicios de Facturación y, por lo tanto, YiMi no será responsable en forma alguna ni conjunta de tales obligaciones del Tercero Autorizado." +"</p>" +
                  "<p>" +"- Facturación en nombre del Socio No Conductor por un tercero." +"</p>" +
                  "<p>" +"Será aplicable al Socio No Conductor que durante el proceso de registro en la aplicación YiMi Fleet no proporcionó su información fiscal completa, ya sea:" +"</p>" +
                  "<p>" +"- no tienen un Registro Federal de Contribuyentes ('RFC') o Certificado de Firma Digital o “CSD”)," +"</p>" +
                  "<p>" +"- no ha proporcionado un CSD válido al Tercero Autorizado" +"</p>" +
                  "<p>" +"- su CSD no se encuentra vigente, o" +"</p>" +
                  "<p>" +"- no cumple con ningún otro requisito para emitir facturas." +"</p>" +
                  "<p>" +"Para estos casos las siguientes opciones serían aplicables:" +"</p>" +
                  "<p>" +"1) Si el Socio No Conductor no cuenta con RFC, o no se lo proporciona a YiMi durante el proceso de registro. En este caso, ya que durante el proceso de registro el Socio No Conductor proporcionó su Código Único de Registro de Población ('CURP'), el Socio No Conductor acepta expresamente que YiMi o cualquier otro tercero puede y debe registrar al Socio No Conductor en el Servicio de Administración Tributaria ('SAT'), usando el CURP del Socio No Conductor, para que el Socio No Conductor pueda obtener su RFC y, por lo tanto, pueda cumplir con sus obligaciones tributarias en México." +"</p>" +
                  "<p>" +"2) Si el Socio No Conductor no proporciona un CSD válido y vigente. En este caso, el Socio No Conductor ya tiene un RFC, que se le proporcionó a YiMi, pero no tiene el CSD para emitir facturas." +"</p>" +
                  "<p>" +"Para los dos escenarios anteriores, el Socio No Conductor acepta y reconoce su aceptación de los términos de los siguientes acuerdos:" +"</p>" +
                  "<p>" +"- Contrato de Comisión Comercial, que se está ejecutando entre el Socio No Conductor y el emisor de facturas en nombre del Socio No Conductor ('Emisor'), según el cual el Emisor actuará como un agente de comisión del Socio No Conductor para la emisión de facturas en nombre del Socio No Conductor." +"</p>" +
                  "<p>" +"- Contrato de Servicios de Facturación, que se está ejecutando entre el Socio No Conductor y el Tercero Autorizado, según la cual el Tercero Autorizado procesará las facturas en nombre y bajo el nombre del Emisor, que a su vez emitirá las facturas en nombre del Socio No Conductor." +"</p>" +
                  "<p>" +"En estos escenarios, el Emisor facturará a los Pasajeros, en nombre y por cuenta del Socio No Conductor, en su calidad de agente de comisión comercial, en el entendimiento de que el Tercero Autorizado continuará siendo la parte responsable del procesamiento de las facturas, por lo tanto, el Socio No Conductor acepta los términos de ambos acuerdos, el Acuerdo de la Comisión Comercial y el Acuerdo de Servicios de Facturación." +"</p>" +
                  "<p>" +"El Socio No Conductor autoriza a YiMi a retener los honorarios que se pagarán a el Emisor y el Tercero Autorizado por sus servicios de facturación y comisiones, y a pagarlos en nombre del Socio No Conductor a el Emisor y el Tercero Autorizado." +"</p>" +
                  "<p>" +"El Socio No Conductor acepta que YiMi podrá, a su entera discreción, absorber el pago de las tarifas a el Tercero Autorizado y el Emisor en nombre del Socio No Conductor, como incentivo. YiMi puede decidir dejar de absorber el pago de esas tarifas en cualquier momento que lo considere conveniente." +"</p>" +
                  "<p>" +"El Socio No Conductor está de acuerdo, para todos los fines legales, que YiMi no será parte del Acuerdo de Servicios de Facturación ni del Acuerdo de la Comisión Comercial. En este sentido, la participación de YiMi consiste en permitir que los Socios No Conductores acepten los términos del Acuerdo de la Comisión Comercial y el Acuerdo de Servicios de Facturación, al dar a conocer esos términos por solicitud y del Socio No Conductor a YiMi. El Tercero Autorizado y el Emisor serán los únicos responsables de sus obligaciones en virtud del Acuerdo de Servicios de Facturación y en virtud del Acuerdo de la Comisión Comercial, y, por lo tanto, YiMi no será responsable ni de ninguna manera responsable por tales obligaciones del Tercero Autorizado o el Emisor." +"</p>" +
                  "<p>" +"- Facturación para Socios No Conductores existentes" +"</p>" +
                  "<p>" +"Para el caso de los Socios No Conductores existentes que ya operan bajo la aplicación de YiMi Fleet, en cualquier momento a discreción de YiMi, se le puede solicitar a los Socios No Conductores que proporcionen su información fiscal para cumplir con la cláusula 4.6.1." +"</p>" +
                  "<p>" +"Considerando la información proporcionada por el Socio No Conductor, el Socio No Conductor acepta y reconoce su aceptación a lo establecido en la cláusula 4.6.1, reconociendo que su registro, o la prestación de servicios bajo la aplicación YiMi Fleet pueden ser cancelados o suspendidos por YiMi si el Socio No Conductor no proporciona dicha información y/o no acepta los términos de la cláusula 4.6.1." +"</p>" +
                  "<p>" +"4.7. Los servicios de telecomunicaciones y las tarifas en las que se incurra por el uso de YiMi Fleet, deberán ser proporcionadas y cargadas por el operador de telecomunicaciones, no por YiMi." +"</p>" +
                  "<p style='font-weight: bold;'>" +"5. Garantías de servicio" +"</p>" +
                  "<p>" +"5.1. En caso de cualquier daño extracontractual causado a un tercero imputable al Socio No Conductor, el Socio No Conductor será responsable de cualquier compensación correspondiente. En caso de daño extracontractual causado por culpa del Socio No Conductor, o cualquier pérdida causada a la Compañía debido al incumplimiento por parte del Socio No Conductor a estos Términos y Condiciones, la Compañía tiene derecho a reclamar una compensación de parte del Socio No Conductor." +"</p>" +
                  "<p>" +"5.2. El Socio No Conductor reconoce que no existe una relación laboral o subordinada entre el Socio No Conductor y YiMi o cualquiera de sus afiliadas, derivada de todas y cada una de las actividades realizadas por el Socio No Conductor a las cuales les son aplicables estos Términos y Condiciones, de conformidad con las leyes y reglamentos laborales, de seguridad social y fiscales aplicables en México." +"</p>" +
                  "<p style='font-weight: bold;'>" +"6. Garantías de servicio" +"</p>" +
                  "<p>" +"6.1. Si el Socio No Conductor incumple cualquier contrato que haya celebrado con YiMi o sus filiales, la Compañía podrá, a su entera discreción, dar por terminados los presentes Términos y Condiciones con el Socio No Conductor según requiera el caso." +"</p>" +
                  "<p>" +"6.2. El Socio No Conductor se obliga a indemnizar a la Compañía y a los funcionarios, consejeros y empleados de la Compañía inmediatamente que se le requiera, por todas las reclamaciones, responsabilidades, daños, costos y gastos, incluyendo honorarios de abogados, derivados de cualquier incumplimiento de los presentes Términos y Condiciones celebrados por el Socio No Conductor y YiMi o cualquier otra responsabilidad derivada del uso de YiMi Fleet por parte del Socio No Conductor." +"</p>" +
                  "<p>" +"6.3. Si el vehículo del servicio no coincide con la información registrada, incluyendo placas falsas, póliza de seguro no válida, marca de vehículo falsa, el Socio No Conductor pagará a YiMi una multa de MX $1,500 (mil quinientos pesos) y YiMi, mientras tanto, tendrá derecho a dar por terminado el contrato con el Socio No Conductor y dejar de prestar servicios permanentemente para el Socio No Conductor." +"</p>" +
                  "<p>" +"6.4. La Compañía tendrá derecho a cobrar a la parte responsable cualquier cantidad que supere el monto de la indemnización que corresponda conforme a la ley, así como a tomar medidas en contra de las partes o infractoras que incumplieron." +"</p>" +
                  "<p style='font-weight: bold;'>" +"7. Suspensión y terminación" +"</p>" +
                  "<p>" +"7.1. La Compañía determinará, a su entera discreción, si ha ocurrido un incumplimiento de los presentes Términos y Condiciones por el uso por parte del Socio No Conductor de YiMi Fleet. Cuando haya ocurrido un incumplimiento de estos Términos y Condiciones, la Compañía podrá tomar las medidas que considere adecuadas." +"</p>" +
                  "<p>" +"7.2. Un incumplimiento de los presentes Términos y Condiciones podrá resultar, de manera enunciativa más no limitativa, en las siguientes medidas:" +"</p>" +
                  "<p>" +"- En una advertencia." +"</p>" +
                  "<p>" +"- Revelación de información relevante a las autoridades." +"</p>" +
                  "<p>" +"- Suspensión y/o retiro inmediato, temporal o permanente del derecho Socio No Conductor de utilizar YiMi Fleet." +"</p>" +
                  "<p>" +"- Acciones legales y demandas en contra del Socio No Conductor para obtener el reembolso de todos los costos sobre una base de indemnización (incluyendo, sin limitación, costos razonables administrativos y legales) que resulten del incumplimiento." +"</p>" +
                  "<p>" +"- Acciones legales adicionales en contra del Socio No Conductor." +"</p>" +
                  "<p style='font-weight: bold;'>" +"8. Restricciones Regulatorias Locales" +"</p>" +
                  "<p>" +"YiMi Fleet no está dirigida a persona alguna en cualquier jurisdicción en la que (debido a la nacionalidad, residencia u otro motivo) el acceso o disponibilidad de YiMi Fleet esté prohibido o pueda estar sujeto a cualquier restricción, incluyendo el registro u otros requerimientos dentro de dicha jurisdicción. YiMi se reserva el derecho de limitar el acceso a YiMi Fleet a cualquiera de estas personas. Las personas que accedan a YiMi Fleet lo hacen por iniciativa propia y serán responsables de cumplir con las leyes y reglamentos locales aplicables. YiMi no será responsable frente a ningún usuario por pérdida o daño alguno, ya sea conforme una disposición contractual, por responsabilidad civil (incluyendo negligencia), incumplimiento de un deber conforme a la ley o por otro motivo, aun cuando sea previsible, derivado de o relacionado con el uso por una persona en una jurisdicción donde el acceso o la disponibilidad de YiMi Fleet esté prohibido o sujeto cualquier restricción. En caso de duda, el Socio No Conductor deberá obtener asesoría legal independiente." +"</p>" +
                  "<p style='font-weight: bold;'>" +"9. No Garantías" +"</p>" +
                  "<p>" +"YiMi Fleet se ofrece “en el estado en que se encuentra” y no se otorga garantía alguna, ni expresa ni implícita, con respecto al YiMi Fleet." +"</p>" +
                  "<p>" +"Salvo por lo expresamente establecido en los presentes Términos y Condiciones, todas las garantías, condiciones y declaraciones, expresas o implícitas por ley o de alguna manera indicadas por YiMi (incluyendo, sin limitación, garantías en cuanto a calidad satisfactoria, idoneidad para un fin o pericia y cuidado) quedan excluidas por esta disposición cuando la ley lo permita." +"</p>" +
                  "<p style='font-weight: bold;'>" +"10. Limitación de la Responsabilidad de YiMi" +"</p>" +
                  "<p>" +"10.1. La información proporcionada y los Servicios recomendados al Socio No Conductor en los sitios web de YiMi o YiMi Fleet son únicamente para referencia del Socio No Conductor. YiMi hará esfuerzos razonables para garantizar la precisión de la información proporcionada, en el entendido, no obstante, que YiMi no garantiza que dicha información esté libre de cualquier error, defecto, software malicioso o virus." +"</p>" +
                  "<p>" +"10.2. YiMi no será responsable por daño alguno que resulte del uso del (o cualquier imposibilidad de usar el) sitio web de YiMi o YiMi Fleet. Asimismo, YiMi no será responsable por daño alguno que resulte del uso de (o cualquier imposibilidad de usar) las herramientas de comunicación electrónica de los sitios web de YiMi o YiMi Fleet, incluyendo, sin limitación, daños causados por fallas de transmisión, mal funcionamiento de Internet o retraso en las comunicaciones electrónicas, intercepción o manipulación de comunicaciones electrónicas por un tercero o programas de cómputo utilizados para la comunicación electrónica y transmisión del virus, falta de energía, huelgas u otras disputas laborales, disturbios, insurrecciones, revueltas, terremotos, incendios, inundación, tormentas, explosiones, guerras; actos del gobierno, órdenes de autoridades judiciales o administrativas o cualquier otra causa de fuerza mayor u omisión de terceros." +"</p>" +
                  "<p>" +"10.3. YiMi no será responsable por daños indirectos, emergentes, especiales, ejemplares, punitivos o incidentales, incluyendo pérdida de utilidades, pérdida de información, lesiones o daños materiales relacionados con o que de otra manera resulten de cualquier uso de los Servicios, independientemente de la negligencia (que sea activa, afirmativa, única o concurrente) de YiMi, aún si YiMi ha sido advertida de la posibilidad de tales daños." +"</p>" +
                  "<p>" +"10.4. YiMi no asume responsabilidad alguna con respecto a la precisión, integridad, suficiencia y confiabilidad de la información y contenido incluido en YiMi Fleet o en los sitios web de YiMi, incluyendo sin limitación textos, imágenes, datos, opiniones, páginas web o enlaces, a pesar de sus esfuerzos de proporcionar información precisa y exhaustiva en la medida posible. YiMi se deslinda de cualquier responsabilidad por cualquier error u omisión y no otorga garantía expresa o implícita alguna." +"</p>" +
                  "<p style='font-weight: bold;'>" +"11. Autorización y Licencia" +"</p>" +
                  "<p>" +"11.1. Sujeto al cumplimiento por parte del Socio No Conductor con los presentes Términos y Condiciones, YiMi otorga al Socio No Conductor una licencia limitada, no exclusiva y no transferible para descargar e instalar una copia de las aplicaciones en un solo dispositivo móvil que el Socio No Conductor posea o controle para utilizar dicha copia de las aplicaciones únicamente para su uso personal." +"</p>" +
                  "<p>" +"11.2. El Socio No Conductor no podrá: (1) otorgar licencias o sub-licencias, vender, revender, transmitir, ceder, distribuir o de otra manera explotar comercialmente o poner a disposición de terceros los servicios o aplicaciones en forma alguna; (2) modificar o crear obras derivadas basadas en los Servicios o las aplicaciones; (3) crear “enlaces” de Internet a los Servicios, o “enmarcar” o “reproducir” cualquier aplicación en cualquier otro servidor o dispositivo inalámbrico o basado en el Internet; (4) llevar a cabo ingeniería de reversa o acceder a las aplicaciones con el fin de diseñar o crear un producto o Servicio competitivo, diseñar o crear un producto utilizando ideas o gráficos similares a los Servicios o las aplicaciones, o copiar cualesquier ideas, características, funciones o gráficos de los Servicios o las aplicaciones; o (5) lanzar un programa o script automatizado, o cualquier programa que pueda hacer múltiples solicitudes a servidores por segundo, o que dificulte u obstaculice indebidamente la operación y/o desempeño de los Servicios o las aplicaciones." +"</p>" +
                  "<p>" +"11.3. Asimismo, el Socio No Conductor no deberá: (1) enviar spam o mensajes duplicados o no solicitados en contravención a las leyes aplicables; (2) enviar o almacenar material violatorio, obsceno, amenazante, difamatorio o que de otra manera sea ilegal o ilícito, incluyendo material que infrinja los derechos de privacidad de terceros; (3) enviar o almacenar material que contenga virus de software, gusanos, caballos troyanos u otro código informático, archivos, scripts, agentes o programas perjudiciales; (4) interferir o afectar la integridad o el funcionamiento de los sitios web de YiMi, sus aplicaciones, los Servicios o los datos contenidos en los mismos; ni (5) intentar obtener acceso no autorizado al sitio web de YiMi, sus aplicaciones, los Servicios o sistemas o redes relacionados." +"</p>" +
                  "<p>" +"11.4. YiMi tendrá derecho a investigar y promover un juicio por cualquiera de los incumplimientos antes mencionados la medida permitida por la ley. YiMi podrá cooperar y asistir con las autoridades encargadas del orden público en las demandas en contra de cualquier Socio No Conductor que haya incumplido los presentes Términos y Condiciones. Si YiMi determina que cualquier contenido infringe los presentes Términos y Condiciones o de otra manera perjudica al sitio web de YiMi, YiMi Fleet y/o los Servicios o aplicaciones relacionados, YiMi se reserva el derecho de eliminar o prohibir el acceso a dicho contenido en cualquier momento sin previa notificación" +"</p>" +
                  "<p style='font-weight: bold;'>" +"12. Política de propiedad intelectual" +"</p>" +
                  "<p>" +"12.1. YiMi y sus filiales son titulares de los derechos de propiedad intelectual de todo el contenido distribuido en YiMi Fleet, incluyendo, sin limitación, el software proporcionado y los productos o servicios relacionados, y tales derechos de propiedad intelectual están protegidos por las leyes. La falta de una declaración de titularidad en cierto contenido no implica que YiMi no tenga la titularidad del mismo o no pueda hacer valer sus derechos sobre el mismo y el Socio No Conductor respetará los legítimos derechos e intereses del titular y utilizará dicho contenido legalmente de conformidad con las leyes y reglamentos aplicables y el principio de buena fe." +"</p>" +
                  "<p>" +"12.2. Sin el consentimiento por escrito de YiMi, ninguna persona física o moral utilizará, copiará, modificará, hará extractos de, incluirá con otros productos para su uso o venta, vinculará ni transmitirá vía un híper-vínculo, almacenará en un sistema de recuperación de información ni utilizará para ningún otro fin comercial cualquier parte del software, de los productos o servicios, de la información o las palabras antes mencionadas en forma alguna bajo ninguna circunstancia, excepto para la descarga o impresión para uso personal no comercial, en el entendido de que no se realizará modificación alguna a lo anterior, y que la declaración de derechos de autor u otra titularidad contenida en los mismos se conservará." +"</p>" +
                  "<p>" +"12.3. Las marcas registradas y logotipos (en lo sucesivo conjuntamente denominados como las “Marcas”) utilizadas y mostradas en dicho software ya sea que estén registradas o no registradas, constituirán las Marcas de YiMi y sus filiales en la industria de contratación de servicios de transporte privado terrestre y otros campos relacionados, mismas que están protegidas por las leyes. Ninguna persona utilizará contenido alguno de dicho software, “YiMi”, “YiMi Pasajero”, “YiMi Fleet” y nombres similares, así como las Marcas en forma alguna sin el consentimiento previo y por escrito de YiMi." +"</p>" +
                  "<p>" +"12.4. Si el Socio No Conductor imprime, copia, descarga, modifica o vincula cualquier parte del Contenido disponible a través de la página web o la aplicación, en incumplimiento de los presentes Términos y Condiciones, el derecho del Socio No Conductor de utilizar el Sitio Web de la Compañía y la aplicación podrán suspenderse inmediatamente y el Socio No Conductor deberá, a discreción de la Compañía, devolver o destruir cualesquier copias (electrónicas o en otro formato) de los materiales que haya realizado el Socio No Conductor." +"</p>" +
                  "<p style='font-weight: bold;'>" +"13. Servicios y enlaces de terceros" +"</p>" +
                  "<p>" +"Durante el uso de las páginas web y aplicaciones relevantes, YiMi podrá, de tiempo en tiempo, proporcionar al Socio No Conductor enlaces a sitios web propiedad de y controlados por terceros, para facilitar la comunicación del Pasajero, la compra de productos o servicios, o para participar en actividades promocionales ofertadas por dichos terceros. Al hacer clic en dichos enlaces, el Socio No Conductor abandonará el sitio web de YiMi o YiMi Fleet y visitará sitios web alojados por dichos terceros que están fuera del control de YiMi, y donde dichos terceros han elaborado sus propios términos, condiciones y políticas de privacidad. Por lo tanto, YiMi no será responsable del contenido y las actividades de dichas páginas web y YiMi no asumirá obligación alguna al respecto. El Socio No Conductor entenderá plenamente el contenido y las actividades de dichos sitios web y asumirá plenamente la responsabilidad legal y los riesgos derivados de la navegación o acceso a dichos sitios web por parte del Pasajero." +"</p>" +
                  "<p style='font-weight: bold;'>" +"14. Término" +"</p>" +
                  "<p>" +"14.1. Los presentes Términos y Condiciones entre el Socio No Conductor y YiMi no tendrán un término de vigencia establecido." +"</p>" +
                  "<p>" +"14.2. Si el Socio No Conductor comete cualquiera de los siguientes actos, YiMi tendrá derecho a dar por terminados los presentes Términos y Condiciones en cualquier momento, con efectos inmediatos (es decir, el Socio No Conductor tendrá prohibido utilizar YiMi Fleet y los Servicios):" +"</p>" +
                  "<p>" +"- si el Socio No Conductor viola o incumple cualquier término de los presentes Términos y Condiciones;" +"</p>" +
                  "<p>" +"- a la entera discreción de YiMi, si el Socio No Conductor abusa de YiMi Fleet, los Servicios, o el Sitio Web de YiMi." +"</p>" +
                  "<p>" +"14.3. Aunque YiMi de por terminado los presentes Términos y Condiciones, el Socio No Conductor será responsable de cualquier daño o perjuicio que pueda derivar de dicho incumplimiento." +"</p>" +
                  "<p>" +"14.4  YiMi no estará obligada a notificar la terminación de los presentes Términos y Condiciones con anticipación. Después de la terminación, YiMi enviará la notificación respectiva de conformidad con los presentes Términos y Condiciones." +"</p>" +
                  "<p style='font-weight: bold;'>" +"15. Fuerza Mayor" +"</p>" +
                  "<p>" +"En caso de que se presente una circunstancia de fuerza mayor, la parte afectada podrá suspender temporalmente el cumplimiento de sus obligaciones conforme al presente instrumento hasta que el efecto de dicha causa de fuerza mayor cese, y no incurrirá en incumplimiento de contrato; en el entendido, no obstante que dicha parte hará su mejor esfuerzo para resolver dicha causa y mitigar las pérdidas. Fuerza mayor significa cualquier causa impredecible e inevitable (aun cuando sea previsible) fuera del control de las partes que impida, afecte o demore el cumplimiento por una parte de todas o cualquiera de sus obligaciones conforme a los presentes Términos y Condiciones. Dichas causas incluyen, sin limitación, terremotos, guerra, modificación de las leyes reglamentos y políticas gubernamentales, virus de cómputo, ataques de hackers o suspensión de servicios prestados por empresas de telecomunicación." +"</p>" +
                  "<p style='font-weight: bold;'>" +"16. Disposiciones Generales" +"</p>" +
                  "<p>" +"16.1. Si se declara la nulidad de algún término de los presentes Términos y Condiciones, los demás términos subsistirán y su exigibilidad no se verá afectada, YiMi determinará si continuará cumpliendo o no con dichos términos." +"</p>" +
                  "<p>" +"16.2. YiMi podrá entregar una notificación publicando una notificación general en su sitio web y/o en YiMi Fleet o enviando un correo electrónico o mensaje de texto a la dirección de correo electrónico o número de teléfono móvil registrado en la información de la cuenta del Socio No Conductor. Las notificaciones, que podrán publicarse de tiempo en tiempo, constituirán parte de los presentes Términos y Condiciones." +"</p>" +
                  "<p>" +"16.3. El Socio No Conductor no cederá ninguno de los derechos conforme a los presentes Términos y Condiciones sin el consentimiento previo y por escrito de YiMi." +"</p>" +
                  "<p style='font-weight: bold;'>" +"17. Otros Términos Aplicables" +"</p>" +
                  "<p>" +"Los presentes Términos y Condiciones hacen referencia a los siguientes términos adicionales, los cuales también serán aplicables al Socio No Conductor al usar los Sitios Web, el contenido, los productos, los Servicios y aplicaciones de YiMi, mismos que, debido al uso, el Socio No Conductor se obliga a cumplir:" +"</p>" +
                  "<p>" +"17.1.	Política de Privacidad de YiMi Fleet que establece los términos conforme a los cuales se procesarán los datos personales y otras informaciones recopilados, o proporcionados por el Socio No Conductor." +"</p>" +
                  "<p style='font-weight: bold;'>" +"18. Ley Aplicable y Jurisdicción" +"</p>" +
                  "<p>" +"Los presentes Términos y Condiciones se regirán por las leyes aplicables en México. Cualquier conflicto, reclamación o controversia derivada de o relacionada con el incumplimiento, terminación, cumplimiento, interpretación o validez de los presentes Términos y Condiciones o el uso del sitio web de YiMi o YiMi Fleet, se someterá a la jurisdicción de un tribunal competente de la Ciudad de México, México y el Socio No Conductor en este acto expresa e irrevocablemente renuncia a cualquier otra jurisdicción que pueda corresponderle en virtud de sus domicilios presentes o futuros." +"</p>" +
                  "<p style='font-weight: bold;'>" +"19. Subsistencia" +"</p>" +
                  "<p>" +"Aun cuando los presentes Términos y Condiciones se den por terminados o anulen, subsistirán las disposiciones relacionadas con la responsabilidad por incumplimiento del Socio No Conductor, las cláusulas de propiedad intelectual, obligación de confidencialidad del Socio No Conductor, ley aplicable y jurisdicción." +"</p>"
              }}
            />
          </View>
        </View>
      );
    }
  }

  export default Terminos;
